development:
  adapter: postgresql
  database: fatcatty_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: fatcatty_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: fatcatty_production
  pool: 5
  timeout: 5000
